name: CI

# Trigger the workflow on push to main, or on pull request
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        gap-version:
          - devel
          - v4.15.0-beta1
          - v4.14
          - v4.13
          - v4.12
          - v4.11
          - v4.10

    steps:
      # the order of the checkout actions is important because all contents of
      # the target folder of the checkout action is removed
      - uses: gap-actions/setup-cygwin@v2
        if: ${{ matrix.os == 'windows-latest' }}
      - uses: actions/checkout@v5
        with:
          repository: gap-packages/example
      - uses: actions/checkout@v5
        with:
          path: this-action/
      - uses: gap-actions/setup-gap@v3
      - uses: ./this-action/
